apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: micropets-catalog-location
  description: The catalog for the micropets application
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./cats/catalog-component.yaml
    - ./dogs/catalog-component.yaml
    - ./fishes/catalog-component.yaml
    - ./pets/catalog-component.yaml
    - ./gui/catalog-component.yaml
    
 