apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: micropets-catalog-location
  description: The catalog for the micropets application
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:        
    - https://github.com/bmoussaud/micropets-dogs-golang/blob/main/catalog-component.yaml
    - https://github.com/bmoussaud/micropets-fishes-golang/blob/main/catalog-component.yaml
    - https://github.com/bmoussaud/micropets-pets-golang/blob/main/catalog-component.yaml
    - https://github.com/bmoussaud/micropets-gui-angular-js/blob/main/catalog-component.yaml
    - ./catalog/micropet-system.yaml
    - ./catalog/cloudapps-domain.yaml
    - ./catalog/the-pet-team.yaml
    - https://github.com/bmoussaud/micropets-elephants/blob/main/catalog-component.yaml
    
 
