apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gui  
  description: Micropets GUI Service
  tags:
    - web
    - tanzu
    - js
    - ui  
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/component=gui'
    'github.com/project-slug': 'bmoussaud/microgui-app/gui'
  links:
    - url: http://front.tap.aks.mytanzu.xyz/
      title: 'Micropets UI Information'
      icon: locallibrary
spec:
  type: website
  lifecycle: experimental
  owner: the-pet-team
  system: micropets
  dependsOn: [Component:micropet-service-pets]
  