apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  name: gui
  labels:
    app.tanzu.vmware.com/workload-type: micropets-delivery
spec:
  params:
  - name: environment
    value: aws/aws-front
  - name: application
    value: micropets/20220329
  serviceAccountName: cartographer-deliverable-sa
  source:
    git:
      ref:
        branch: main
      url: http://github.com/bmoussaud/micropets-app-gitops.git
  