apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: gui
  labels:
    app.tanzu.vmware.com/workload-type: micropet-service-git-gui
spec:
  serviceAccountName: cartographer-workload-sa
  source:
    git:
      url: https://github.com/bmoussaud/micropets-app/
      ref:
        branch: master
  params:
    - name: broker_service
      value: "/"
    - name: color
      value: blue
  
