apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: the-pet-team
  description: La Pet Team
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    displayName: The Famous Pet Team
    email: team-a@example.com
    picture: https://api.dicebear.com/6.x/bottts/svg?seed=Daisy
  #parent: development
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bmoussaud
spec:
  profile:
    displayName: Benoit Moussaud
    email: benoit@example.com
    picture: https://avatars.githubusercontent.com/u/283453?v=4
  memberOf: [the-pet-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: acastellan
spec:
  profile:
    displayName: Arnaud Castellan
    email: arnaud@example.com
    picture: https://api.dicebear.com/6.x/notionists/svg?seed=Precious
  memberOf: [the-pet-team]
 
