apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: the-pet-team
  description: La Pet Team
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    displayName: The Famous Pet Team
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  #parent: development
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bmoussaud
spec:
  profile:
    displayName: Benoit Moussaud
    email: guest1@example.com
    picture: https://avatars.githubusercontent.com/u/283453?v=4
  memberOf: [the-pet-team]
