apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: cats
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: cats
spec:  
  source:
    git:
      url: https://github.com/bmoussaud/micropets-app/
      ref:
        branch: master
  params:
    - name: mode
      value: "RANDOM_NUMBER"
    - name: port
      value: 7002
    - name: observability
      value: true
