---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-configuration     
data:
  values.yml: |  
    service:  
      name: dogs
      port: 7003
      mode: RANDOM_NUMBER
      replicas: 1
      version: latest
      virtual_host: front.mytanzu.xyz
    registry:
      server: harbor.mytanzu.xyz/library
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: sample-app
spec:
  serviceAccountName: default  
  fetch:
    - git:
        url: https://github.com/bmoussaud/micropets-app
        ref: master
        subPath: cluster/tap/app-operator/kapp
  template:
    - ytt:
        ignoreUnknownComments: true
        valuesFrom:
          - configMapRef:
              name: sample-app-configuration      
  deploy:
    - kapp:
        intoNs: truc