apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: skip-test-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: micropets-skip-test
spec:
  params:
  - name: source-url
    type: string
  - name: source-revision
    type: string
  tasks:
  - name: test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    taskSpec:
      metadata: {}
      params:
      - name: source-url
        type: string
      - name: source-revision
        type: string
      spec: null
      steps:
      - image: zenika/alpine-chrome:102-with-node-16
        name: angular-test-chrome-headless
        resources: {}
        script: |-
          cd `mktemp -d`
          wget -qO- $(params.source-url) | tar xvz -m          
          pwd
          echo "!!!! skip the tests !"