---
apiVersion: v1
kind: Secret
metadata:
  name: gui-config
  labels:
    app.kubernetes.io/part-of: gui
type: Opaque
stringData:
  type: app-configuration
  config.json: |-
    {  
      "petServiceUrl": "https://pets.dev-tap.tap4.eu.aks.mytanzu.xyz",
      "stage": "Demo",
      "debug": "False",
      "stage_color": "green",
      "load_one_by_one": "True"
    }
