---
apiVersion: v1
kind: Secret
metadata:
  name: gui-config
  labels:
    app.kubernetes.io/part-of: gui
type: Opaque
stringData:
  type: app-configuration
  config.json: |-
    {  
      "petServiceUrl": "/pets",
      "stage": "demo",
      "debug": "False",
      "stage_color": "red",
      "load_one_by_one": "True"
    }
