apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: gui-angular-js
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: micropets
    app.kubernetes.io/name: gui
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  build:
    env:
      - name: X_BP_NODE_OPTIMIZE_MEMORY
        value: "true"
      - name: LOG_LEVEL
        value: DEBUG
      - name: NODE_OPTIONS
        value: "--max_old_space_size=3072"
      - name: MEMORY_AVAILABLE
        value: "4096"
  source:
    git:
      url: https://github.com/bmoussaud/micropets-app/
      ref:
        branch: master
    subPath: gui
  serviceClaims:
    - name: app-config
      ref:
        apiVersion: v1
        kind: Secret
        name: gui-config
  env:
    - name: SERVICE_BINDING_ROOT
      value: "/workspace/dist/assets"
    - name: PETS_SERVICE
      value: http://pets-golang.micropets-int/pets
  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: skip-test
    - name: scanning_source_policy
      value: scan-policy-angular
    - name: scanning_image_policy
      value: scan-policy-angular
