apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pets  
  description: Micropets Pets Service
  tags:
    - web
    - tanzu
    - golang  
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=pets'
    'github.com/project-slug': 'bmoussaud/micropets-app/pets'
spec:
  type: service
  lifecycle: experimental
  owner: the-pet-team
  system: micropets
  dependsOn: [Component:cats,Component:dogs,Component:fishes]
  providesApis:
    - pets